POST http://127.0.0.1:8000/api/users/register/ HTTP/1.1
content-type: application/json
{
    "username": "john",
    "email": "john@mail.com",
    "password": "john123!"
}
#########

POST http://127.0.0.1:8000/api/users/login/ HTTP/1.1
content-type: application/json

{
    "username": "john",
    "password": "john123!"
}
#######


POST http://127.0.0.1:8000/api/users/login/ HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "4796"
}
#####


GET  http://127.0.0.1:8000/api/users/logout/ HTTP/1.1
Authorization: Token 84c0a399c96f8b975f588bcaad3442aa850819d1
#######