# Generated by Django 5.1.2 on 2025-01-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='price',
            new_name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='requires_payment',
        ),
        migrations.RemoveField(
            model_name='event',
            name='requires_rsvp',
        ),
    ]
